import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblEmail: String = "Email"
    static let kMsgBmiBodyMass: String = "BMI (Body Mass Index)"
    static let kMsgEverybodyCanT: String = "Everybody Can Train"
    static let kMsgDonTHaveAnA: String = "Don’t have an account yet? Register"
    static let kLblSeeMore: String = "See more"
    static let kLblCheck: String = "Check"
    static let kMsgYouHaveANorm: String = "You have a normal weight"
    static let kMsgDonTHaveAnA2: String = "Don’t have an account yet? "
    static let kLblX: String = "X"
    static let kLblHeyThere: String = "Hey there,"
    static let kLblLogin: String = "Login"
    static let kLblWelcomeBack2: String = "Welcome Back,"
    static let kMsg180CaloriesBu: String = "180 Calories Burn | 20minutes"
    static let kLblViewMore: String = "View More"
    static let kMsg200CaloriesBu: String = "200 Calories Burn | 30minutes"
    static let kMsgForgotYourPas: String = "Forgot your password?"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblTodayTarget: String = "Today Target"
    static let kLblFitnest: String = "Fitnest"
    static let kLbl201: String = "20,1"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblWelcomeBack: String = "Welcome Back"
    static let kMsgLowerbodyWorko: String = "Lowerbody Workout"
    static let kLblGetStarted: String = "Get Started"
    static let kLblPassword: String = "Password"
    static let kLblFitnestx: String = "FitnestX"
    static let kLblOr: String = "Or"
    static let kLblAbWorkout: String = "Ab Workout"
    static let kLblRegister: String = "Register"
    static let kMsgFullbodyWorkou: String = "Fullbody Workout"
    static let kLblActivityStatus: String = "Activity Status"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblStefaniWong: String = "Stefani Wong"
    static let kLblLatestWorkout: String = "Latest Workout"
}
